# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/works/OpenCV-HellowWorld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/works/OpenCV-HellowWorld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/works/OpenCV-HellowWorld/CMakeFiles /mnt/d/works/OpenCV-HellowWorld/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/works/OpenCV-HellowWorld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OutputBinaryImage

# Build rule for target.
OutputBinaryImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OutputBinaryImage
.PHONY : OutputBinaryImage

# fast build rule for target.
OutputBinaryImage/fast:
	$(MAKE) -f CMakeFiles/OutputBinaryImage.dir/build.make CMakeFiles/OutputBinaryImage.dir/build
.PHONY : OutputBinaryImage/fast

#=============================================================================
# Target rules for targets named OutputGrayImage

# Build rule for target.
OutputGrayImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OutputGrayImage
.PHONY : OutputGrayImage

# fast build rule for target.
OutputGrayImage/fast:
	$(MAKE) -f CMakeFiles/OutputGrayImage.dir/build.make CMakeFiles/OutputGrayImage.dir/build
.PHONY : OutputGrayImage/fast

#=============================================================================
# Target rules for targets named DisplayImage

# Build rule for target.
DisplayImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DisplayImage
.PHONY : DisplayImage

# fast build rule for target.
DisplayImage/fast:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/build
.PHONY : DisplayImage/fast

DisplayImage.o: DisplayImage.cpp.o

.PHONY : DisplayImage.o

# target to build an object file
DisplayImage.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/DisplayImage.cpp.o
.PHONY : DisplayImage.cpp.o

DisplayImage.i: DisplayImage.cpp.i

.PHONY : DisplayImage.i

# target to preprocess a source file
DisplayImage.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/DisplayImage.cpp.i
.PHONY : DisplayImage.cpp.i

DisplayImage.s: DisplayImage.cpp.s

.PHONY : DisplayImage.s

# target to generate assembly for a file
DisplayImage.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/DisplayImage.cpp.s
.PHONY : DisplayImage.cpp.s

OutputBinaryImage.o: OutputBinaryImage.cpp.o

.PHONY : OutputBinaryImage.o

# target to build an object file
OutputBinaryImage.cpp.o:
	$(MAKE) -f CMakeFiles/OutputBinaryImage.dir/build.make CMakeFiles/OutputBinaryImage.dir/OutputBinaryImage.cpp.o
.PHONY : OutputBinaryImage.cpp.o

OutputBinaryImage.i: OutputBinaryImage.cpp.i

.PHONY : OutputBinaryImage.i

# target to preprocess a source file
OutputBinaryImage.cpp.i:
	$(MAKE) -f CMakeFiles/OutputBinaryImage.dir/build.make CMakeFiles/OutputBinaryImage.dir/OutputBinaryImage.cpp.i
.PHONY : OutputBinaryImage.cpp.i

OutputBinaryImage.s: OutputBinaryImage.cpp.s

.PHONY : OutputBinaryImage.s

# target to generate assembly for a file
OutputBinaryImage.cpp.s:
	$(MAKE) -f CMakeFiles/OutputBinaryImage.dir/build.make CMakeFiles/OutputBinaryImage.dir/OutputBinaryImage.cpp.s
.PHONY : OutputBinaryImage.cpp.s

OutputGrayImage.o: OutputGrayImage.cpp.o

.PHONY : OutputGrayImage.o

# target to build an object file
OutputGrayImage.cpp.o:
	$(MAKE) -f CMakeFiles/OutputGrayImage.dir/build.make CMakeFiles/OutputGrayImage.dir/OutputGrayImage.cpp.o
.PHONY : OutputGrayImage.cpp.o

OutputGrayImage.i: OutputGrayImage.cpp.i

.PHONY : OutputGrayImage.i

# target to preprocess a source file
OutputGrayImage.cpp.i:
	$(MAKE) -f CMakeFiles/OutputGrayImage.dir/build.make CMakeFiles/OutputGrayImage.dir/OutputGrayImage.cpp.i
.PHONY : OutputGrayImage.cpp.i

OutputGrayImage.s: OutputGrayImage.cpp.s

.PHONY : OutputGrayImage.s

# target to generate assembly for a file
OutputGrayImage.cpp.s:
	$(MAKE) -f CMakeFiles/OutputGrayImage.dir/build.make CMakeFiles/OutputGrayImage.dir/OutputGrayImage.cpp.s
.PHONY : OutputGrayImage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... OutputBinaryImage"
	@echo "... rebuild_cache"
	@echo "... OutputGrayImage"
	@echo "... DisplayImage"
	@echo "... DisplayImage.o"
	@echo "... DisplayImage.i"
	@echo "... DisplayImage.s"
	@echo "... OutputBinaryImage.o"
	@echo "... OutputBinaryImage.i"
	@echo "... OutputBinaryImage.s"
	@echo "... OutputGrayImage.o"
	@echo "... OutputGrayImage.i"
	@echo "... OutputGrayImage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

